version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  text_worker:
    build: ./workers/text_worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
